### ISSUE TITLE
Empty file after conversion

### ISSUE THREAD

**Issue by laceysanderson** [UofS-Pulse-Binfo/posconvert#1]
We have observed in some cases, the pos convert tripal job will appear to be working correctly (i.e iteratively creating the file with the new positions) throughout the process. But at the end, it appears the file is written over causing an empty file to be served to the user. This was observed with a large file but we were unable to replicate the issue even with the same file.

**Comment by laceysanderson** [comment]
@carolyncaron we still need to look into this bug more thoroughly to ensure it will not be a problem.

**Comment by carolyncaron** [comment]
I started up a tripal daemon on fresh, and input the same file which previously caused this issue. The job took 4 hours 15 minutes to run, but I received a converted file in the end. The log was updated at the end of the job, and while there were no errors reported, the very next line after job completion stood out to me:
`[2017-05-23 19:20:43]  7821              	 Job completed at 23 May 2017 19:20:43 with a status of 'Completed'`
`[2017-05-23 19:20:43]  7821               Run Loop Taking Too Long. Duration: 15,316.517 Interval: 20`

The next thing I'll try to recreate the issue is to run this job and then try adding other jobs to the queue. Any other ideas?

**Comment by carolyncaron** [comment]
I also doubled the size of the file (by duplicating the lines) and it successfully converted in ~8.5 hours. There is still nothing unusual in the daemon log, other than "Run Loop Taking Too Long" message, which @laceysanderson suggests is just the PHP Daemon library not expecting long-running jobs. We have a slight suspicion that the PHP buffer may have been having sporadic issues with either the size of a file or the length of time required to write to an output file, but I am unsure how to proceed with testing and/or fixing this.

I feel that this issue is either very specific to the main KnowPulse site, or has been "accidentally" addressed in recent code development, as we can no longer reproduce it. However, the process of testing posconvert with large files has exposed a few concerns:
1. There is a limit (125 Mb I think?) on file size for the upload to work. I think it would be helpful for the user to know ahead of time about this limit, especially since it takes over a minute for the error message to display.
2. It takes ~1 hour to process 25000 lines. Perhaps we want to impose a limit on the number of lines to prevent people from running long jobs, since this prevents other users from running jobs until it has completed. We could also warn the user if their file is pushing that limit that things will take a while to run.
3. After a user has clicked Submit and the job is running, the user should be discouraged from returning to the form to "try again" or upload another file - this will only tie up the job system further and cause potential for issues (perhaps such as the one I've been unable to reproduce). A warning message on the download page should be sufficient for this. They can also be warned against navigating away from the page to ensure they have access to the download link.

@reynoldtan, do you think you could implement these user warnings for this module?

**Comment by reynoldtan** [comment]
Warnings:

1. To implement this, we get the actual php settings (ini settings for max file upload) and display that value to user, along with the warning - file should be less or not exceeding this value. This will reflect the actual server setting in the event admin will replace this value in the future.

2. How many lines should we warn user? and for We could also warn the user if their file is pushing that limit that things will take a while to run. - please explain.

3. Not sure how to prevent user from doing this but I can check the tripal job queue and see if the current user has ongoing posconvert process and not show the form.

**Comment by carolyncaron** [comment]
I think we can merge **1** and **2** into a single message, along the lines of: 
> Posconvert is limited to files that are less than ___ Mb or 20 000 lines (not including the header). It will take up to an hour to convert a file of 20 000 lines. If you have a larger file, please contact us directly for help with converting your file.

I put 20 000 lines because I think this is typical of an unfiltered RIL population. But anything beyond that, they should really come talk to us anyway, since ideally their file would be filtered prior to converting it...

For **3**, can we provide a warning message once they reach the download page? Something like:
> Please do not navigate away from this page if you wish to download your converted file. Once the progress bar has started, your file is already submitted to the system and it will need to complete before any other files can start converting (**_this also includes other users_**). Thank you for your patience!

Although, I do also like your suggestion of hiding the form if they already have a file downloading. Perhaps it is a good measure to implement that along with the warning?

@laceysanderson, what do you think of the wording for the warnings?

**Comment by laceysanderson** [comment]
Fixed via PR.
